// NOTE: Assertions have been autogenerated by utils/update_test_checks.py
// RUN: %clangxx -O0 %S/UnreachableRT.cpp -o %t.UnreachableRT.o -c
// RUN: %clangxx -O0 -mllvm -enable-instrumentor -mllvm -instrumentor-read-config-file=%S/UnreachableRT.json %t.UnreachableRT.o -o %t %s 
// RUN: not %t 2>&1 | FileCheck %s --check-prefix=FIRST
// RUN: not %t arg 2>&1 | FileCheck %s --check-prefix=SECOND

static int foobar() {
  __builtin_unreachable();
}


int main(int argc, char **argv) {
  if (argc > 1)
    foobar();
  else
    __builtin_unreachable();
}

// FIRST:  Hit unreachable #1
// SECOND: Hit unreachable #2
