; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: not opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/test_malformed_filter.json -S 2>&1 | FileCheck %s --check-prefix=A
; RUN: not opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/test_filter_config_bad.json -S 2>&1 | FileCheck %s --check-prefix=B
; RUN: not opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/test_filter_errors.json -S 2>&1 | FileCheck %s --check-prefix=C

; A: error: malformed filter expression for instrumentation opportunity 'load': expected integer value at position 2
; B: error: malformed filter expression for instrumentation opportunity 'function': expected property name, got 'unknown'
; C: error: malformed filter expression for instrumentation opportunity 'load': expected comparison operator after property 'sync_scope_id'
; C: error: malformed filter expression for instrumentation opportunity 'function': unclosed string literal starting at position 6

define i32 @test() {
entry:
  %l = load i32, ptr null
  ret i32 %l
}
